### ISSUE TITLE
More work to cleanup build and deployment 

### ISSUE THREAD

**Issue by rantav** [reversim/reversim-summit-2020#45]
@jondot

Running and testing:

Run in dev mode: 

	1. Run mongod in the background
	2. make run

Cleanup: 

	make clean

Test production build: 

	make build-prod

Most of the work had been done in this branch https://github.com/reversim/reversim-summit-2020/pull/42/files which is now merged b/c it's too large anyway... so just start a new branch

## What's left todo (I guess that's a partial list, but let's start with that) 

- [ ] Search for TODO(rantav) in client/config/webpack.config.prod.js
	Return UglifyJS and deal with the the problematic joi-browser.min.js
	Eventually return eslint, commented out b/c it very slow. Can you make it faster?!...

- [ ] Upgrade all security issues (npm audit). The auto fix breaks the site. in `client/packase.json`. `cd client; npm audit`

- [ ] Upgrade webpack to 4.x.x? (It is one of the security issues) 

- [ ] Move to npx? Is it worth it?

- [ ] Move from babel-core to @babel/core? What's the difference?

**Comment by jondot** [comment]
Ticking off a few boxes:

* move to npx -- nah. move to yarn and base everything on it - yes. not urgent from what I can tell.
* upgrade to webpack 4.x -- yes, I gave it an hour now, the codebase _really_ resists the move, falling back to deal with the rest of the stuff. In either way, webpack is'nt _really_ a security risk since it's only used for build. (for starter, I've separated dev from prod deps now).
* babel-core / @babel/code -- a major update for babel. not sure if it's worth it right now but should be down the road
* eslint being slow -- will check. either way I'm more in favor of IDE-integrated eslint rather than a blocker-policy linting for the entire project when we're dealing with very small teams and fluid dev process.

I'll continue and update.

**Comment by jondot** [comment]
Update:

* I believe we can kill off UglifyJS. The site is already open source, so no need to make it 'hard' to read the code on the one hand, and given gzip on the backend -- no effect for compression.

**Comment by jondot** [comment]
First draft of fixes. LMK what you think of the approach + fixes.

**Comment by rantav** [comment]
think we're done here
